version: '3.8'

services:
  nodex:
    build: .
    image: marhaburrisqi/nodex:latest
    container_name: nodex
    restart: unless-stopped
    network_mode: host  
    environment:
      - PROVIDER=cloudflare          
      - DOMAIN=home.example.com
      - TOKEN=your_api_token_here
      - ZONE_ID=your_zone_id_here    # Wajib untuk Cloudflare
      - RECORD_TYPE=A                
      - INTERVAL=300                
      - MODE=daemon
      - FORCE=false
    volumes:
      - nodex_cache:/tmp           
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.1'

volumes:
  nodex_cache: